### ISSUE TITLE
Migrate to @typescript-eslint/eslint-plugin v8

### ISSUE THREAD

**Issue by asimonok** [grafana/eslint-config-grafana#39]
Currently, the package can't be used with `@typescript-eslint/eslint-plugin` v8 and the following errors appear

```
error  Definition for rule '@typescript-eslint/type-annotation-spacing' was not found  @typescript-eslint/type-annotation-spacing
```

It happens because some rules have been deprecated - https://typescript-eslint.io/rules/type-annotation-spacing/

Rules should be updated to be compatible with the latest major version

**Comment by jackw** [comment]
@asimonok Thanks for opening this issue. We recently published version 8 of our eslint config which should fix this issue and allow you to use `@typescript-eslint/eslint-plugin@^8.9.0`. Please could you give it a go and report back here if this issue is not solved?

Note that this is a major version change with a breaking change. We have moved from this package declaring it's own dependencies to using peerDependencies. This should give everyone an easier time with using the versions of the eslint plugins they want to with their project without conflicting or needing to bump deps in this config. Please make sure to install the peer dependencies when testing this out.

**Comment by mikhail-vl** [comment]
@jackw Thank you. We are reviewing it and will use in the new version of our plugins.

**Comment by mikhail-vl** [comment]
@jackw Works great! You are welcome to close.
